"""sessions

Revision ID: 411fad47dc63
Revises: 99ed737d5b9d
Create Date: 2017-03-04 21:49:21.937116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411fad47dc63'
down_revision = '99ed737d5b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('real_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_session')
    # ### end Alembic commands ###
