"""fractions

Revision ID: 2c05b97972fa
Revises: 640b5299e6b4
Create Date: 2017-02-17 01:35:38.184628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c05b97972fa'
down_revision = '640b5299e6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fraction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.Unicode(), nullable=True),
        sa.Column('weight', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraction_title'), 'fraction', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraction_title'), table_name='fraction')
    op.drop_table('fraction')
    # ### end Alembic commands ###
