"""gc attributes

Revision ID: 640b5299e6b4
Revises: 8bf2a034b373
Create Date: 2017-02-15 11:17:51.768752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640b5299e6b4'
down_revision = '8bf2a034b373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_character', sa.Column('description', sa.Unicode(), nullable=True))
    op.add_column('game_character', sa.Column('dx', sa.Integer(), nullable=True))
    op.add_column('game_character', sa.Column('ht', sa.Integer(), nullable=True))
    op.add_column('game_character', sa.Column('iq', sa.Integer(), nullable=True))
    op.add_column('game_character', sa.Column('st', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_character', 'st')
    op.drop_column('game_character', 'iq')
    op.drop_column('game_character', 'ht')
    op.drop_column('game_character', 'dx')
    op.drop_column('game_character', 'description')
    # ### end Alembic commands ###
