"""game characters

Revision ID: 8bf2a034b373
Revises: 5c6a141c3642
Create Date: 2017-02-14 16:08:52.907357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf2a034b373'
down_revision = '5c6a141c3642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'game_character',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('charname', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_character_charname'), 'game_character', ['charname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_character_charname'), table_name='game_character')
    op.drop_table('game_character')
    # ### end Alembic commands ###
