"""game_session_table

Revision ID: 19c8c10e9c8d
Revises: 50e43f641568
Create Date: 2017-09-16 17:02:41.655014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c8c10e9c8d'
down_revision = '50e43f641568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('real_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_session')
    # ### end Alembic commands ###
