"""galaxy_names

Revision ID: 2fc6532c3d29
Revises: 0c83d0e69bec
Create Date: 2017-09-20 11:04:13.396494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc6532c3d29'
down_revision = '0c83d0e69bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galaxy_name')
    # ### end Alembic commands ###
