"""blue_star

Revision ID: 7a3aa562c645
Revises: c5c418709bfc
Create Date: 2017-09-22 13:25:17.548998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3aa562c645'
down_revision = 'c5c418709bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_type', sa.Column('blue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('star_type', 'blue')
    # ### end Alembic commands ###
