"""planet_table

Revision ID: 87af9ace9e7c
Revises: e8eaaa8b805e
Create Date: 2017-09-23 09:36:02.346560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87af9ace9e7c'
down_revision = 'e8eaaa8b805e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atmosphere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surface_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=32), nullable=True),
    sa.Column('size', sa.Float(precision=2), nullable=True),
    sa.Column('from_sun', sa.Float(precision=2), nullable=True),
    sa.Column('day', sa.Float(precision=2), nullable=True),
    sa.Column('year', sa.Float(precision=2), nullable=True),
    sa.Column('gravity', sa.Float(precision=2), nullable=True),
    sa.Column('moons', sa.Integer(), nullable=True),
    sa.Column('tilt', sa.Float(precision=2), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('star_id', sa.Integer(), nullable=True),
    sa.Column('planet_type_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('atmosphere_id', sa.Integer(), nullable=True),
    sa.Column('surface_map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atmosphere_id'], ['atmosphere.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.ForeignKeyConstraint(['planet_type_id'], ['planet_type.id'], ),
    sa.ForeignKeyConstraint(['star_id'], ['star.id'], ),
    sa.ForeignKeyConstraint(['surface_map_id'], ['surface_map.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    op.drop_table('surface_map')
    op.drop_table('planet_type')
    op.drop_table('environment')
    op.drop_table('atmosphere')
    # ### end Alembic commands ###
