"""gender_table

Revision ID: 8ceb209b22c2
Revises: 72ab1e11a957
Create Date: 2018-05-12 12:04:44.180676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import sql

# revision identifiers, used by Alembic.
revision = '8ceb209b22c2'
down_revision = '72ab1e11a957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    gender_table = sql.table('gender',
        sql.column('id', sa.Integer()),
        sql.column('title', sa.String()),
        # sql.column('id', sa.Integer(), nullable=False),
        # sql.column('title', sa.String(length=32), nullable=False),
        # sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(gender_table, [
        {'id': 1, 'title': 'Male'},
        {'id': 2, 'title': 'Female'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gender')
    # ### end Alembic commands ###
