"""star_table

Revision ID: ae813c267ec8
Revises: 8d78aefac4d4
Create Date: 2017-09-20 14:51:49.051553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae813c267ec8'
# down_revision = '8d78aefac4d4'
down_revision = 'db274dfe98e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=True),
    sa.Column('star_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['galaxy_id'], ['galaxy.id'], ),
    sa.ForeignKeyConstraint(['star_type_id'], ['star_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star')
    # ### end Alembic commands ###
