"""campaign_description

Revision ID: c1d2ea6b6746
Revises: ae813c267ec8
Create Date: 2017-09-21 16:09:06.334139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2ea6b6746'
down_revision = 'ae813c267ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('description', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'description')
    # ### end Alembic commands ###
