"""star_types

Revision ID: db274dfe98e7
Revises: c1d2ea6b6746
Create Date: 2017-09-22 11:03:27.529252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db274dfe98e7'
# down_revision = 'c1d2ea6b6746'
down_revision = '8d78aefac4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star_type')
    # ### end Alembic commands ###
