"""planet_earthlike

Revision ID: ddfe0536f53b
Revises: 8076d8002cd5
Create Date: 2017-09-24 19:32:43.371790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfe0536f53b'
down_revision = '8076d8002cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet_type', sa.Column('earth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet_type', 'earth')
    # ### end Alembic commands ###
