"""star_type

Revision ID: e8eaaa8b805e
Revises: 6e948a0f2d25
Create Date: 2017-09-22 15:10:15.049847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8eaaa8b805e'
down_revision = '6e948a0f2d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('star', sa.Column('star_type_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'star', 'star_type', ['star_type_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'star', type_='foreignkey')
    # op.drop_column('star', 'star_type_id')
    pass
    # ### end Alembic commands ###
