#! /usr/bin/env python
# -*- coding:utf-8 -*-
DND3 = [
    {"book": "PHB", "title": "1.Abilities"},
    {"book": "PHB", "title": "2.Races"},
    {"book": "PHB", "title": "3.Classes"},
    {"book": "PHB", "title": "4.Skills"},
    {"book": "PHB", "title": "5.Feats"},
    {"book": "PHB", "title": "6.Desription"},
    {"book": "PHB", "title": "7.Equipment"},
    {"book": "PHB", "title": "8.Combat"},
    {"book": "PHB", "title": "9.Adventuring"},
    {"book": "PHB", "title": "10.Magic"},
    {"book": "PHB", "title": "11.Spells"},

    {"book": "PHB2", "title": "1.New Classes"},
    {"book": "PHB2", "title": "2.Expanded Classes"},
    {"book": "PHB2", "title": "3.New Feats"},
    {"book": "PHB2", "title": "4.New Spells"},
    {"book": "PHB2", "title": "5.Identity"},
    {"book": "PHB2", "title": "6.Group"},
    {"book": "PHB2", "title": "7.Affilations"},
    {"book": "PHB2", "title": "8.Rebuilding"},
    {"book": "PHB2", "title": "A.Quick Creation"},

    {"book": "DMG", "title": "1.Game"},
    {"book": "DMG", "title": "2.Rules"},
    {"book": "DMG", "title": "3.Adventures"},
    {"book": "DMG", "title": "4.NPC"},
    {"book": "DMG", "title": "5.Campaigns"},
    {"book": "DMG", "title": "6.Characters"},
    {"book": "DMG", "title": "7.Magic Items"},
    {"book": "DMG", "title": "8.Glossary"},

    {"book": "DMG2", "title": "1.Game"},
    {"book": "DMG2", "title": "2.Adventures"},
    {"book": "DMG2", "title": "3.Campaigns"},
    {"book": "DMG2", "title": "4.Saltmarsh"},
    {"book": "DMG2", "title": "5.NPC"},
    {"book": "DMG2", "title": "6.Characters"},
    {"book": "DMG2", "title": "7.Magic Items"},
]

DND1 = [
    {"book": "Cycl", "title": "1.Steps"},
    {"book": "Cycl", "title": "2.Classes"},
    {"book": "Cycl", "title": "3.Spells"},
    {"book": "Cycl", "title": "4.Equipment"},
    {"book": "Cycl", "title": "5.Other"},
    {"book": "Cycl", "title": "6.Movement"},
    {"book": "Cycl", "title": "7.Encounters"},
    {"book": "Cycl", "title": "8.Combat"},
    {"book": "Cycl", "title": "9.Mass Combat"},
    {"book": "Cycl", "title": "10.Experience"},
    {"book": "Cycl", "title": "11.Creating NPC"},
    {"book": "Cycl", "title": "12.Strongholds"},
    {"book": "Cycl", "title": "13.Gamemastering"},
    {"book": "Cycl", "title": "14.Monsters"},
    {"book": "Cycl", "title": "15.Immortals"},
    {"book": "Cycl", "title": "16.Treasure"},
    {"book": "Cycl", "title": "17.Environment"},
    {"book": "Cycl", "title": "18.Planes"},
    {"book": "Cycl", "title": "19.Variant"},
    {"book": "Cycl", "title": "A1.World"},
    {"book": "Cycl", "title": "A2.Conversions"},
    {"book": "Cycl", "title": "A3.Record Sheets"},

    {"book": "CRB", "title": "FastNPC"},
    {"book": "CRB", "title": "Campaign"},
    {"book": "CRB", "title": "World"},
    {"book": "CRB", "title": "Plots"},
    {"book": "CRB", "title": "Primary NPC"},
    {"book": "CRB", "title": "Secondary NPC"},
    {"book": "CRB", "title": "PC"},
    {"book": "CRB", "title": "Maps"},
    {"book": "CRB", "title": "Calendar"},
    {"book": "CRB", "title": "Log"},
    {"book": "CRB", "title": "Random Encounters"},
    {"book": "CRB", "title": "Homerules"},
    {"book": "CRB", "title": "Pockets"},
    {"book": "CRB", "title": "Tavern"},
]
